### ISSUE TITLE
option to not auto evaluate in motippets

### ISSUE THREAD

**Issue by wooloogooloo** [narcode/codeklavier-extensions#1]
Dear CodeKlavier master @narcode , 
@tmhglnd and I were wondering if we can have an option in the motippets part of CK to also not auto evaluate and have a manual evaluate. However, some parts would still want the auto-evaluate. Is this something you could relatively easily adjust for us soon?

Thanks, 
Your trusty source for driven development, 
@wooloogooloo

**Comment by narcode** [comment]
If you explain it better to me it should be possible. Shall I talk this with Timo or with you woologgoloo?

**Comment by wooloogooloo** [comment]
At the moment, all the commands in the motipetts part of the ini file auto-evaluate. We would like for this not to be the case and have a seperate evaluate function (this is like how we have it in the hello world part). However, it would be good to still have an option to have some of the motippets, particularly the mini-motifs auto evaluate.

But yes, discuss with Timo if im not making sense. In fact, i believe he wanted to discuss something else with you anyway.

Thanks, 
Anne

**Comment by narcode** [comment]
I will talk to him too but it makes all the sense of the world. What about having a section in the .ini file for motifs without auto-evaluate? i would call it [lazy motifs] so you just put the motifs you want there that don't evaluate immediately. Is this an idea? and what kind of motifs would you like to have there? if it's all of the current ones (chords, melodic, etc) then maybe its better to add a lazy flag instead of a new section. can you or @tmhglnd shed some light here?

**Comment by wooloogooloo** [comment]
I think adding a lazy flag would ultimately be best. I can imagine this might be relevant to other CK extensions as well.

Thanks!

**Comment by narcode** [comment]
Ok will work on it and let you know when its done. Working branch is ck_dev…

**Comment by wooloogooloo** [comment]
YOu closed this issue
